[project]
name = "project3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "opencv-python==4.12.0.88",
    "setuptools==80.9.0",
    "streamlit>=1.50.0",
    "tensorflow",
]
